name: app_receitas
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  sembast: ^3.5.0+1
  uuid: ^4.3.3
  path: ^1.8.3
  path_provider: ^2.0.15
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  get_it: ^7.6.2
  flutter_native_splash: ^2.3.2
  mocktail: ^1.0.0
  email_validator: ^2.1.17
  dio: ^5.3.3
  flutter_carousel_widget: ^2.1.2
  image_picker: ^1.0.4
  flutter_staggered_grid_view: ^0.7.0
  http_parser: ^4.0.2

  duration_time_picker:
    path: ../packages/duration_time_picker
  google_fonts: ^6.2.1
  flutter_quill:
    path: ../packages/flutter-quill
  vsc_quill_delta_to_html: ^1.0.4
  flutter_widget_from_html_core: ^0.14.11
  dotted_border: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  image: "assets/images/logo.png"
  android: true
  color: "#FFFFFF"
  android_12:
    image: "assets/images/logo.png"
    icon_background_color: "#101636"